-- Traditional Chinese (Hong Kong) ontology hint expansion for semantic resolver category coverage.
insert into public.category_ontology (
  category_key,
  side,
  section,
  parent_concept,
  definition,
  multilingual_hints,
  examples,
  is_active
)
values
('Groceries', 'expense', 'Food', 'Groceries', 'Supermarkets and everyday food staples bought for home.', '["grocery","supermarket","whole foods","trader joes","kroger","safeway","aldi","walmart grocery","超市","雜貨","百佳","惠康","market place","citysuper"]'::jsonb, '["Carrefour"]'::jsonb, true),
('Refund', 'income', 'Income', 'Reversal', 'Money returned for a prior purchase or charge reversal.', '["refund","reversal","returned payment","退款","退費","回水","交易撤銷"]'::jsonb, '["Card Refund"]'::jsonb, true),
('Tax Refund', 'income', 'Income', 'Tax', 'Tax refund received from a government authority.', '["tax refund","irs refund","revenue refund","退稅","稅務退款"]'::jsonb, '["IRS Refund"]'::jsonb, true),
('Insurance (Other)', 'expense', 'Protection', 'Insurance', 'General insurance premiums that are not better matched to a specific policy type.', '["insurance","premium","保險","保費","保單"]'::jsonb, '["Policy Premium"]'::jsonb, true),
('Phone', 'expense', 'Utilities', 'Telecom', 'Mobile or phone service charges.', '["mobile","phone","wireless","cellular","singtel","birdie","at&t","t mobile","tmobile","verizon","手機","電話費","流動","電訊","通訊","3hk","csl","smt"]'::jsonb, '["Singtel"]'::jsonb, true),
('Coffee & Cafes', 'expense', 'Food', 'Cafe', 'Coffee shops, cafes, tea houses, and similar drink-first stops.', '["coffee","cafe","espresso","latte","cappuccino","starbucks","costa coffee","peets","咖啡","咖啡店","星巴克","太平洋咖啡"]'::jsonb, '["Starbucks"]'::jsonb, true),
('Restaurants', 'expense', 'Food', 'Dining', 'Sit-down dining, casual restaurants, and meal-focused eateries.', '["restaurant","bistro","grill","diner","steakhouse","sushi","ramen","pizza","餐廳","食肆","飯店","茶餐廳"]'::jsonb, '["Din Tai Fung"]'::jsonb, true),
('Fast Food', 'expense', 'Food', 'Quick Service', 'Quick-service chains and takeaway meal counters.', '["mcdonalds","burger king","kfc","taco bell","wendys","popeyes","subway","快餐","麥當勞","肯德基","漢堡王"]'::jsonb, '["McDonald''s"]'::jsonb, true),
('Movies & Events', 'expense', 'Lifestyle', 'Events', 'Cinema tickets, live events, and ticketed outings.', '["movie","cinema","imax","theatre","theater","ticketmaster","concert","event ticket","電影","戲院","門票","演唱會","活動票"]'::jsonb, '["CINEMA.COM"]'::jsonb, true),
('Streaming Services', 'expense', 'Lifestyle', 'Digital Media', 'Recurring audio or video streaming platforms.', '["spotify","netflix","disney","hulu","youtube premium","apple tv","max","串流","影音平台","disney+"]'::jsonb, '["Spotify"]'::jsonb, true),
('Flights', 'expense', 'Travel', 'Air Travel', 'Airline tickets and flight-related travel bookings.', '["flight","airline","airways","airport","air ticket","boarding","united airlines","delta","american airlines","cathay pacific","singapore airlines","航班","航空","機票","登機","國泰","港航","香港快運"]'::jsonb, '["United Airlines"]'::jsonb, true),
('Internet', 'expense', 'Utilities', 'Connectivity', 'Home, office, or broadband internet service charges.', '["internet","broadband","fiber","fibre","wifi","hkbn","xfinity","verizon fios","寬頻","上網","網絡","互聯網","hgc","netvigator"]'::jsonb, '["HKBN"]'::jsonb, true),
('Salary', 'income', 'Income', 'Payroll', 'Employer payroll deposits and salary payments.', '["payroll","salary","wages","direct deposit","employer","薪金","工資","出糧","人工","薪酬"]'::jsonb, '["GUSTO PAY"]'::jsonb, true),
('Public Transit', 'expense', 'Transport', 'Transit', 'Subway, rail, bus, ferry, and other public transport fares.', '["metro","subway","bus","train","rail","transit","octopus","mtr","地鐵","巴士","火車","電車","港鐵","八達通","渡輪"]'::jsonb, '["MTR"]'::jsonb, true),
('Bank Fees', 'expense', 'Banking', 'Fees', 'Bank service fees, finance charges, and transaction fees.', '["bank fee","monthly service fee","maintenance fee","overdraft fee","atm fee","手續費","銀行費","服務費","透支費","atm費"]'::jsonb, '["Overseas Fee"]'::jsonb, true),
('Food Delivery', 'expense', 'Food', 'Delivery', 'Delivered meals and app-based food orders.', '["doordash","uber eats","grubhub","deliveroo","food delivery","外賣","送餐","foodpanda","ubereats","戶戶送"]'::jsonb, '["Uber Eats"]'::jsonb, true),
('Hotels & Lodging', 'expense', 'Travel', 'Lodging', 'Hotels, resorts, inns, and short-stay lodging.', '["hotel","resort","lodging","motel","inn","suites","marriott","hilton","hyatt","holiday inn","airbnb","booking.com","酒店","旅館","住宿","民宿","度假村"]'::jsonb, '["Marriott"]'::jsonb, true),
('Rideshare', 'expense', 'Transport', 'Ride Service', 'App rides, taxi-like ride services, and point-to-point paid rides.', '["uber","lyft","rideshare","ride","taxi","grab","的士","網約車","滴滴"]'::jsonb, '["Uber"]'::jsonb, true),
('Parking', 'expense', 'Transport', 'Parking', 'Parking lots, garages, parking meters, and parking operators.', '["parking","garage","car park","parking meter","wilson parking","停車","泊車","停車場","咪錶"]'::jsonb, '["Wilson Parking"]'::jsonb, true),
('Tolls', 'expense', 'Transport', 'Road Fees', 'Road tolls and expressway charges.', '["toll","tollway","expressway","road charge","e-tag","ez pass","隧道費","路費","收費公路","高速費"]'::jsonb, '["EZ Pass"]'::jsonb, true),
('Gas & Fuel', 'expense', 'Transport', 'Fuel', 'Vehicle fuel purchases and fuel station payments.', '["gas","fuel","petrol","diesel","shell","bp","chevron","exxon","油站","汽油","柴油","加油","esso","caltex"]'::jsonb, '["Shell"]'::jsonb, true),
('Rent', 'expense', 'Housing', 'Housing Payment', 'Recurring housing rent paid to landlord or property manager.', '["rent","apartment rent","tenant","landlord","lease","租金","租屋","租約","業主"]'::jsonb, '["Monthly Rent"]'::jsonb, true),
('Electricity', 'expense', 'Utilities', 'Power Utility', 'Electricity bills and power utility charges.', '["electric","electricity","power bill","utility power","kwh","電費","電力","中電","港燈"]'::jsonb, '["Electric Utility"]'::jsonb, true),
('Water', 'expense', 'Utilities', 'Water Utility', 'Water service and municipal water utility charges.', '["water bill","water utility","water services","waterworks","水費","水務","食水"]'::jsonb, '["Water Utility"]'::jsonb, true),
('Gas & Heating', 'expense', 'Utilities', 'Gas Utility', 'Natural gas and city gas service charges for home or business.', '["gas utility","natural gas","gas bill","city gas","煤氣","石油氣","燃氣","煤氣費","towngas"]'::jsonb, '["Gas Utility"]'::jsonb, true),
('Prescriptions', 'expense', 'Health', 'Pharmacy', 'Prescription and pharmacy retail health purchases.', '["pharmacy","drugstore","prescription","walgreens","cvs","rite aid","藥房","藥局","處方","配藥","萬寧","屈臣氏"]'::jsonb, '["CVS Pharmacy"]'::jsonb, true),
('Dental Care', 'expense', 'Health', 'Dental', 'Dentist, dental clinic, and oral-care service payments.', '["dental","dentist","orthodontist","牙科","牙醫","箍牙"]'::jsonb, '["Dental Clinic"]'::jsonb, true),
('Vision Care', 'expense', 'Health', 'Vision', 'Optical stores, vision care, and eye health services.', '["optical","vision","glasses","contact lenses","optometrist","眼鏡","視光","視力","隱形眼鏡","驗眼"]'::jsonb, '["Optical Center"]'::jsonb, true),
('Fitness & Gym', 'expense', 'Health', 'Fitness', 'Gym memberships, fitness subscriptions, and exercise studios.', '["gym","fitness","yoga","pilates","planet fitness","la fitness","anytime fitness","健身","健身房","瑜伽","普拉提"]'::jsonb, '["Anytime Fitness"]'::jsonb, true),
('Wellness & Spa', 'expense', 'Health', 'Wellness', 'Spa, massage, and wellness treatment services.', '["spa","massage","wellness","sauna","水療","按摩","桑拿","養生"]'::jsonb, '["Wellness Spa"]'::jsonb, true),
('Credit Card Fees', 'expense', 'Banking', 'Card Fees', 'Credit card fees such as annual, late, and foreign transaction fees.', '["late fee","annual fee","cash advance fee","foreign transaction fee","信用卡年費","滯納金","現金透支費","海外交易費"]'::jsonb, '["Card Annual Fee"]'::jsonb, true),
('Taxes', 'expense', 'Government', 'Tax', 'General tax payments to tax authorities.', '["tax","irs","revenue service","tax payment","稅款","交稅","稅務局","政府稅"]'::jsonb, '["Tax Payment"]'::jsonb, true),
('Property Tax', 'expense', 'Government', 'Property Tax', 'Taxes assessed on property ownership and real estate.', '["property tax","real estate tax","物業稅","地稅","差餉"]'::jsonb, '["Property Tax Bill"]'::jsonb, true),
('Bonus', 'income', 'Income', 'Payroll', 'Bonus and commission income from employer or contract work.', '["bonus","commission","花紅","獎金","佣金"]'::jsonb, '["Quarterly Bonus"]'::jsonb, true),
('Interest', 'income', 'Income', 'Yield', 'Interest income credited from savings, deposits, or account balances.', '["interest paid","interest earned","intrst pymnt","int earned","利息","存款利息","利息收入"]'::jsonb, '["INTRST PYMNT"]'::jsonb, true),
('Dividends', 'income', 'Income', 'Investment Income', 'Dividend payouts and related investment distribution income.', '["dividend","div reinvest","div payout","股息","派息","紅利"]'::jsonb, '["Dividend Payout"]'::jsonb, true),
('Cashback & Rewards', 'income', 'Income', 'Rewards', 'Cashback, rebate, and rewards redemption credits.', '["cashback","reward","points redemption","rebate","現金回贈","回贈","積分兌換","返現"]'::jsonb, '["Cashback Reward"]'::jsonb, true),
('Rental Income', 'income', 'Income', 'Property Income', 'Income received from tenants or rental contracts.', '["rent received","rental income","tenant payment","租金收入","收租","租客付款"]'::jsonb, '["Tenant Payment"]'::jsonb, true),
('Freelance', 'income', 'Income', 'Business Income', 'Independent work, client invoices, and business payout income.', '["invoice","client payment","freelance","contract","stripe payout","square payout","shopify payout","自由工作","接案","客戶付款","商業收入","營業收入","合約款"]'::jsonb, '["Client Invoice Payment"]'::jsonb, true),
('Side Hustle', 'income', 'Income', 'Business Income', 'Income from side jobs, extra gigs, and non-primary hustle work.', '["invoice","client payment","freelance","contract","stripe payout","square payout","shopify payout","自由工作","接案","客戶付款","商業收入","營業收入","合約款"]'::jsonb, '["Side Gig Payment"]'::jsonb, true),
('Business', 'income', 'Income', 'Business Income', 'Business revenue, company payouts, and business client settlements.', '["invoice","client payment","freelance","contract","stripe payout","square payout","shopify payout","自由工作","接案","客戶付款","商業收入","營業收入","合約款"]'::jsonb, '["Business Client Payment"]'::jsonb, true)
on conflict (category_key, side)
do update set
  section = excluded.section,
  parent_concept = excluded.parent_concept,
  definition = excluded.definition,
  multilingual_hints = excluded.multilingual_hints,
  examples = excluded.examples,
  is_active = true,
  updated_at = now();
